[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-solver-bm25-plugin"
dynamic = ["readme", "version"]
description = "A question solver plugin for OVOS"
authors = [{ name = "JarbasAi", email = "jarbasai@mailfence.com" }]
license = { text = "MIT" }
requires-python = ">=3.9"
keywords = ["OVOS", "openvoiceos", "plugin", "utterance", "fallback", "query"]

dependencies = [
    "ovos-plugin-manager>=2.2.0",
    "bm25s",
    "quebra-frases>=0.2.0",
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-solver-BM25-plugin"

[project.entry-points."opm.solver.question"]
"ovos-solver-bm25-squad-plugin" = "ovos_bm25_solver.demo:BM25SquadQASolver"
"ovos-solver-bm25-freebase-plugin" = "ovos_bm25_solver.demo:BM25FreebaseQASolver"

[project.entry-points."opm.solver.summarization"]
"ovos-summarizer-bm25" = "ovos_bm25_solver:BM25SummarizerPlugin"

[project.entry-points."opm.solver.reading_comprehension"]
"ovos-evidence-solver-bm25" = "ovos_bm25_solver:BM25SolverPlugin"

[project.entry-points."opm.solver.multiple_choice"]
"ovos-choice-solver-bm25" = "ovos_bm25_solver:BM25MultipleChoiceSolver"

[tool.setuptools]
packages = ["ovos_bm25_solver"]
include-package-data = true

[tool.setuptools.dynamic]
readme = { file = "README.md", content-type = "text/markdown" }
version = { attr = "ovos_bm25_solver.version.__version__" }
